Updated seed data to better reflect Game model.
jebidiah252/usu-gdsf pull request #12
Opened 2022-07-24 00:26 UTC by mpt777

Build a get a getgamebyid method and implemented it on all databases.
(this is my first pull request ever!)

2022-07-24 23:08 UTC, ianjm24 reviewed
This looks good! All I would say is to add a unit test for the getgamebyid function

2022-07-25 19:54 UTC, jebidiah252 requested changes
All of this looks really good. I've made some comments to look over.

2022-07-25 19:54 UTC, jebidiah252 commented on backend/api/robots.go
> +	registerRoute(route{method: http.MethodGet, path: "/robots.txt", handler: robots})
Can you change the path on this from `/robots.txt` to `/robots`? It's not convention to put dots in the route name.

2022-07-25 19:54 UTC, jebidiah252 commented on backend/db/dbSeed.go
> +const JSON_SEED_DATA = `[{"uuid":"1c2b0d0a-934f-4f6d-81f9-116112445ed6","name":"Konklab","description":"infrastructure","useruuid":"091d7c91-91b1-4111-9fa2-9fbdfde7618c","creationdate":"4/18/2022","v
Can we change the version to not look like IP Addresses?

2022-07-25 19:54 UTC, jebidiah252 commented on backend/api/game.go
>  func game(c echo.Context) error {
Can we change this to something like, "GameById"? That will be a little more readable.

2022-07-25 19:54 UTC, jebidiah252 commented on backend/models/game.go
> +	UUID         string
Do we know if there is a uuid library made for go? We could then assign the uuids that are in this struct to be of type uuid instead of string.

2022-07-26 00:35 UTC, mpt777 commented on backend/api/robots.go
> +	registerRoute(route{method: http.MethodGet, path: "/robots.txt", handler: robots})
I just removed this file, no need to have it

2022-07-26 00:36 UTC, mpt777 commented on backend/db/dbSeed.go
> +const JSON_SEED_DATA = `[{"uuid":"1c2b0d0a-934f-4f6d-81f9-116112445ed6","name":"Konklab","description":"infrastructure","useruuid":"091d7c91-91b1-4111-9fa2-9fbdfde7618c","creationdate":"4/18/2022","v
Using my seed data software, I wasn't able to find a comparable value for versions. If you have any suggestions. I would love to hear about them.

2022-07-26 00:36 UTC, mpt777 commented on backend/api/game.go
>  func game(c echo.Context) error {
Yep!

2022-07-26 00:36 UTC, mpt777 commented on backend/models/game.go
> +	UUID         string
Required some reading, but it is done!

2022-07-27 17:07 UTC, jebidiah252 approved these changes
I like the changes made here. I think we'll need to do some refactoring later to change the database to use a uuid instead of a string, but for now, this is something that can be merged.

2022-07-27 17:07 UTC, jebidiah252 commented on backend/models/game.go
> +type ID uuid.UUID
Asking this out of curiosity, but is there a reason that we have ID defined here like this?

2022-07-27 17:08 UTC, merged

2022-07-27 18:44 UTC, mpt777 commented on backend/models/game.go
> +type ID uuid.UUID
No particular reason. Through my perusing of the the style guide it seemed common for attributes of structs to be lowercase, but the boiler plate code we were given was written in pascal case. 
Point being, I was confused and this is what I went with. I'm totally happy to refactor this if needed/wanted :)

2022-07-27 18:46 UTC, mpt777 commented on backend/models/game.go
> +type ID uuid.UUID
I don't think it is needed anymore.
I was using it to test some mongodb things

2022-07-27 18:47 UTC, mpt777 commented
> I like the changes made here. I think we'll need to do some refactoring later to change the database to use a uuid instead of a string, but for now, this is something that can be merged.

What database? MongoDB should be using its own uuid

2022-07-27 19:44 UTC, jebidiah252 commented
> 

I guess this is what I get for not proofreading my comment before submitting. What I should have said was that we should replace the parameter that is passed in for getting a game from a string to a uuid. That's what I wanted to say, but not proofreading made me say something else.

2022-07-27 20:03 UTC, mpt777 commented
> > 
> 
> I guess this is what I get for not proofreading my comment before submitting. What I should have said was that we should replace the parameter that is passed in for getting a game from a string to a uuid. That's what I wanted to say, but not proofreading made me say something else.

Ah, thanks for that clarification!