added data structure for backend models
jebidiah252/usu-gdsf pull request #28
Opened 2022-07-30 18:32 UTC by rohit078689

Added a raw structure and connections and login is yet to be build with other tasks

2022-07-31 16:41 UTC, jebidiah252 requested changes
This looks like a great start here. One thing that I believe should be changed (and I'm looking at @ianjm24 while I say this) is that we could probably change all of the first IDs in each of our structs (i.e. in Game we have GameID) to just being ID (i.e. in the Game struct, we would replace GameID with ID). Let me know if that makes sense.

2022-07-31 16:41 UTC, jebidiah252 commented on backend/models/Gametag.go
> +type GameTag struct {
I think the game tags is something that is a little past MVP, but for now, I have no problem leaving this in here.

2022-07-31 16:41 UTC, jebidiah252 commented on backend/models/UserRoles.go
> +type UserRoles struct {
I don't think that the roles should be a struct here. I was thinking that they could be an enum instead. I'd recommend taking a look at [this](https://www.sohamkamani.com/golang/enums/) article

2022-07-31 16:41 UTC, jebidiah252 commented on backend/models/user.go
> +	UserID       uuid.UUID
UserID is defined twice in this file.

2022-08-01 00:07 UTC, ianjm24 commented
Yes I agree with @jebidiah252 about the IDs. The ID would be for the object itself, and a named ID would be for when one object references another (e.g. a Rating will have both an ID for itself and a GameID for the Game object it references)

2022-08-01 23:49 UTC, rohit078689 commented on backend/models/Gametag.go
> +type GameTag struct {
Implemented changes

2022-08-01 23:50 UTC, rohit078689 commented
Implemented suggested chanegs

2022-08-01 23:53 UTC, jebidiah252 approved these changes
Looks great!

2022-08-01 23:53 UTC, merged

2022-08-01 23:56 UTC, ianjm24 commented on backend/models/game.go
> +	VersionNumber string
The game model will need to have a reference to where its game files are stored. For cloud storage this should just be a URL, so string should be fine.
```suggestion
	VersionNumber string
	GameStorageURL string
```